int tmax();
int test_tmax();
int bitOr(int, int);
int test_bitOr(int, int);
int negate(int);
int test_negate(int);
int isEqual(int, int);
int test_isEqual(int, int);
int isNegative(int);
int test_isNegative(int);
int getByte(int, int);
int test_getByte(int, int);
int addOverflow(int, int);
int test_addOverflow(int, int);
